// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {updater} from '../models';
import {models} from '../models';

export function BackupDatabase(arg1:string):Promise<string>;

export function BulkDeleteRows(arg1:string,arg2:Array<number>):Promise<number>;

export function CancelImport(arg1:string):Promise<boolean>;

export function CheckForUpdate():Promise<updater.Info>;

export function CreateTemplate(arg1:models.Template):Promise<models.Template>;

export function CreateUser(arg1:string,arg2:string,arg3:string,arg4:string):Promise<models.User>;

export function DeleteRow(arg1:string,arg2:number):Promise<void>;

export function DeleteSavedFilter(arg1:string):Promise<void>;

export function DeleteTemplate(arg1:string):Promise<void>;

export function DownloadDataTemplate(arg1:string,arg2:string):Promise<string>;

export function DownloadUpdate(arg1:string,arg2:string):Promise<string>;

export function DuplicateTemplate(arg1:string,arg2:string):Promise<models.Template>;

export function ExportData(arg1:models.ExportRequest,arg2:string):Promise<models.ExportResult>;

export function ExportTemplateSchema(arg1:string):Promise<string>;

export function GetAllSettings():Promise<Record<string, string>>;

export function GetAllTemplates():Promise<Array<models.Template>>;

export function GetAllUsers():Promise<Array<models.User>>;

export function GetAppVersion():Promise<string>;

export function GetCurrentUser():Promise<models.UserSession>;

export function GetDashboardSummary():Promise<models.AppSummary>;

export function GetDataRow(arg1:string,arg2:number):Promise<Record<string, any>>;

export function GetDistinctValues(arg1:string,arg2:string,arg3:string,arg4:number):Promise<Array<models.DistinctValue>>;

export function GetDuplicateGroups(arg1:string,arg2:Array<string>,arg3:string,arg4:number):Promise<Array<models.DuplicateGroup>>;

export function GetImportErrors(arg1:string,arg2:number):Promise<Array<models.ImportError>>;

export function GetImportHistory(arg1:string,arg2:number):Promise<Array<models.ImportHistory>>;

export function GetRecentLogs(arg1:number):Promise<Array<models.ActivityLog>>;

export function GetSavedFilters(arg1:string):Promise<Array<models.SavedFilter>>;

export function GetSetting(arg1:string,arg2:string):Promise<string>;

export function GetTemplateByID(arg1:string):Promise<models.Template>;

export function ImportTemplateSchema(arg1:string):Promise<models.Template>;

export function InstallUpdate():Promise<updater.InstallResult>;

export function Login(arg1:string,arg2:string):Promise<models.UserSession>;

export function Logout():Promise<boolean>;

export function OpenReleasePage(arg1:string):Promise<void>;

export function OpenUpdateFolder():Promise<void>;

export function PreviewExcelFile(arg1:string,arg2:string,arg3:number,arg4:number):Promise<models.ExcelSheetPreview>;

export function QueryData(arg1:models.QueryRequest):Promise<models.QueryResponse>;

export function SaveDataRow(arg1:string,arg2:number,arg3:Record<string, string>):Promise<number>;

export function SaveSavedFilter(arg1:models.SavedFilter):Promise<void>;

export function SelectDirectory(arg1:string):Promise<string>;

export function SelectExcelFile():Promise<string>;

export function SetSetting(arg1:string,arg2:string):Promise<void>;

export function ShowMainWindow(arg1:number,arg2:number,arg3:number,arg4:number):Promise<void>;

export function StartImport(arg1:string,arg2:string,arg3:string):Promise<models.ImportHistory>;

export function TruncateDataset(arg1:string):Promise<void>;

export function UpdatePassword(arg1:string,arg2:string):Promise<void>;

export function UpdateTemplate(arg1:models.Template):Promise<models.Template>;
