// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BackupDatabase(arg1) {
  return window['go']['main']['App']['BackupDatabase'](arg1);
}

export function BulkDeleteRows(arg1, arg2) {
  return window['go']['main']['App']['BulkDeleteRows'](arg1, arg2);
}

export function CancelImport(arg1) {
  return window['go']['main']['App']['CancelImport'](arg1);
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function CreateTemplate(arg1) {
  return window['go']['main']['App']['CreateTemplate'](arg1);
}

export function CreateUser(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateUser'](arg1, arg2, arg3, arg4);
}

export function DeleteRow(arg1, arg2) {
  return window['go']['main']['App']['DeleteRow'](arg1, arg2);
}

export function DeleteSavedFilter(arg1) {
  return window['go']['main']['App']['DeleteSavedFilter'](arg1);
}

export function DeleteTemplate(arg1) {
  return window['go']['main']['App']['DeleteTemplate'](arg1);
}

export function DownloadDataTemplate(arg1, arg2) {
  return window['go']['main']['App']['DownloadDataTemplate'](arg1, arg2);
}

export function DownloadUpdate(arg1, arg2) {
  return window['go']['main']['App']['DownloadUpdate'](arg1, arg2);
}

export function DuplicateTemplate(arg1, arg2) {
  return window['go']['main']['App']['DuplicateTemplate'](arg1, arg2);
}

export function ExportData(arg1, arg2) {
  return window['go']['main']['App']['ExportData'](arg1, arg2);
}

export function ExportTemplateSchema(arg1) {
  return window['go']['main']['App']['ExportTemplateSchema'](arg1);
}

export function GetAllSettings() {
  return window['go']['main']['App']['GetAllSettings']();
}

export function GetAllTemplates() {
  return window['go']['main']['App']['GetAllTemplates']();
}

export function GetAllUsers() {
  return window['go']['main']['App']['GetAllUsers']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetCurrentUser() {
  return window['go']['main']['App']['GetCurrentUser']();
}

export function GetDashboardSummary() {
  return window['go']['main']['App']['GetDashboardSummary']();
}

export function GetDataRow(arg1, arg2) {
  return window['go']['main']['App']['GetDataRow'](arg1, arg2);
}

export function GetDistinctValues(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetDistinctValues'](arg1, arg2, arg3, arg4);
}

export function GetDuplicateGroups(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetDuplicateGroups'](arg1, arg2, arg3, arg4);
}

export function GetImportErrors(arg1, arg2) {
  return window['go']['main']['App']['GetImportErrors'](arg1, arg2);
}

export function GetImportHistory(arg1, arg2) {
  return window['go']['main']['App']['GetImportHistory'](arg1, arg2);
}

export function GetRecentLogs(arg1) {
  return window['go']['main']['App']['GetRecentLogs'](arg1);
}

export function GetSavedFilters(arg1) {
  return window['go']['main']['App']['GetSavedFilters'](arg1);
}

export function GetSetting(arg1, arg2) {
  return window['go']['main']['App']['GetSetting'](arg1, arg2);
}

export function GetTemplateByID(arg1) {
  return window['go']['main']['App']['GetTemplateByID'](arg1);
}

export function ImportTemplateSchema(arg1) {
  return window['go']['main']['App']['ImportTemplateSchema'](arg1);
}

export function InstallUpdate() {
  return window['go']['main']['App']['InstallUpdate']();
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function OpenReleasePage(arg1) {
  return window['go']['main']['App']['OpenReleasePage'](arg1);
}

export function OpenUpdateFolder() {
  return window['go']['main']['App']['OpenUpdateFolder']();
}

export function PreviewExcelFile(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['PreviewExcelFile'](arg1, arg2, arg3, arg4);
}

export function QueryData(arg1) {
  return window['go']['main']['App']['QueryData'](arg1);
}

export function SaveDataRow(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveDataRow'](arg1, arg2, arg3);
}

export function SaveSavedFilter(arg1) {
  return window['go']['main']['App']['SaveSavedFilter'](arg1);
}

export function SelectDirectory(arg1) {
  return window['go']['main']['App']['SelectDirectory'](arg1);
}

export function SelectExcelFile() {
  return window['go']['main']['App']['SelectExcelFile']();
}

export function SetSetting(arg1, arg2) {
  return window['go']['main']['App']['SetSetting'](arg1, arg2);
}

export function StartImport(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartImport'](arg1, arg2, arg3);
}

export function TruncateDataset(arg1) {
  return window['go']['main']['App']['TruncateDataset'](arg1);
}

export function UpdatePassword(arg1, arg2) {
  return window['go']['main']['App']['UpdatePassword'](arg1, arg2);
}

export function UpdateTemplate(arg1) {
  return window['go']['main']['App']['UpdateTemplate'](arg1);
}
